### ISSUE TITLE
403 error

### ISSUE THREAD

**Issue by mindcombatant** [amcoder/curse_client#9]
it worked fine a few days ago, but now, this is my output:
`$ curse show "TerraFirmaCraft Reloaded"

Loading project information from curse
/usr/lib/ruby/2.3.0/net/http/response.rb:120:in `error!': 403 "Site Disabled" (Net::HTTPServerException)
	from /var/lib/gems/2.3.0/gems/curse_client-0.1.4/lib/curse_client/api.rb:59:in `get_json'
	from /var/lib/gems/2.3.0/gems/curse_client-0.1.4/lib/curse_client/api.rb:35:in `addon'
	from /var/lib/gems/2.3.0/gems/curse_client-0.1.4/lib/curse_client/client.rb:39:in `block in addon'
	from /var/lib/gems/2.3.0/gems/curse_client-0.1.4/lib/curse_client/client.rb:67:in `with_authentication'
	from /var/lib/gems/2.3.0/gems/curse_client-0.1.4/lib/curse_client/client.rb:38:in `addon'
	from /var/lib/gems/2.3.0/gems/curse_client-0.1.4/lib/curse_client/client.rb:34:in `find_by_name'
	from /var/lib/gems/2.3.0/gems/curse_client-0.1.4/lib/curse_client/cli.rb:23:in `show'
	from /var/lib/gems/2.3.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
	from /var/lib/gems/2.3.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
	from /var/lib/gems/2.3.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
	from /var/lib/gems/2.3.0/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
	from /var/lib/gems/2.3.0/gems/curse_client-0.1.4/exe/curse:5:in `<top (required)>'
	from /usr/local/bin/curse:23:in `load'
	from /usr/local/bin/curse:23:in `<main>'`

**Comment by amcoder** [comment]
The backend webservice went down. It should be back up now.

**Comment by mindcombatant** [comment]
aah, okay, i wasn't sure if they had changed something with their backend or something. thank you so much for making this program, by the way, it's awesome for us Linux users!
